### ISSUE TITLE
AllAccessDisabled for GEOmetadb.sqlite.gz 

### ISSUE THREAD

**Issue by jwatkins-prometheus** [seandavi/GEOmetadb#8]
I'm getting a 403 error when accessing GEOmetadb.sqlite.gz with getSQLiteFile():
<img width="609" alt="Screen Shot 2022-07-13 at 4 00 02 PM" src="https://user-images.githubusercontent.com/108811069/179012577-bba1d5be-946f-4934-9b72-88af63ecbfa4.png">

When I inspect http://starbuck1.s3.amazonaws.com/sradb/GEOmetadb.sqlite.gz in a browser, I can see an AllAccessDisabled Error:
<img width="777" alt="Screen Shot 2022-07-14 at 10 56 57 AM" src="https://user-images.githubusercontent.com/108811069/179012879-5141e714-aa0a-4e1f-a631-063f1434a586.png">
:

**Comment by maciematt** [comment]
Same here - I've tried multiple times over the last two weeks or so, and have been seeing the same errors.

**Comment by dvera** [comment]
Any updates on this issue?

**Comment by Pedoro47** [comment]
No, I can't find any comments about this issue




2022년 8월 18일 (목) 오전 6:15, Daniel Vera ***@***.***>님이 작성:

**Comment by Romicak** [comment]
I am facing the same issue since July. Getting the following error:
`trying URL 'http://starbuck1.s3.amazonaws.com/sradb/GEOmetadb_demo.sqlite.gz'
Error in download.file(url_geo, destfile = localfile, mode = "wb") : 
  cannot open URL 'http://starbuck1.s3.amazonaws.com/sradb/GEOmetadb_demo.sqlite.gz'
In addition: Warning message:
In download.file(url_geo, destfile = localfile, mode = "wb") :
  cannot open URL 'http://starbuck1.s3.amazonaws.com/sradb/GEOmetadb_demo.sqlite.gz': HTTP status was '403 Forbidden'`

**Comment by Romicak** [comment]
Hi all, it seems there is another Github repository for GEOmetadb with the most recent update being made for this package 10 days ago. Here is the link: https://github.com/zhujack/GEOmetadb

Perhaps we should raise this issue there.

**Comment by YinCY123** [comment]
> 

does this works?

**Comment by Romicak** [comment]
Hi all,

I think the issue is resolved now. I was able to download the sqlite file.

**Comment by maciematt** [comment]
Just tried again, and got the same error:

<img width="1392" alt="Screen Shot 2022-11-06 at 5 49 54 PM" src="https://user-images.githubusercontent.com/3673043/200199617-41e468b9-e17a-4397-85b0-0f698aa980b3.png">
